version: '3'
services:
  db:
   container_name: 'postgresql'
   image: postgres
   restart: always
   environment:
    POSTGRES_PASSWORD: '123456'
    POSTGRES_USER: 'postgres'
    POSTGRES_DB: 'blog'
   ports:
     - '5433:5432'
   volumes:
     - 'pgdata:/var/lib/postgresql/data'
   networks:
     - connect
networks:
  connect:
   driver: bridge
volumes:
  pgdata:
  